name: Ruby
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install RVM
      run: gpg2 --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
      run: curl -sSL https://get.rvm.io | bash -s stable
      run: source /etc/profile.d/rvm.sh
    - name: Install Ruby
      run: rvm install 3.1.2
      run: bundle install
    - name: Run tests
      run: bundle exec rake test
